/* eslint-disable key-spacing,key-spacing,no-trailing-spaces */
/**
 * Created by viktor on 17/7/17.
 */

export const SPROUT = {

  SCREEN_TYPE: 'SCREEN_TYPE',

  // ------------------------ Start & Authentication Screens ------------------------

  // start screen
  START_SCREEN         : 'START_SCREEN',

  // authentication selector screen
  AUTH_SELECTOR_SCREEN : 'AUTH_SELECTOR_SCREEN',

  // authentication screen (signup email)
  SIGNUP_EMAIL: 'SIGNUP_EMAIL',

  // authentication screen (signup)
  AUTHENTICATION_SCREEN: 'AUTHENTICATION_SCREEN',

  // login screen (login)
  LOGIN: 'LOGIN',

  // login PIN
  LOGIN_PIN: 'LOGIN_PIN',

  // touch id screen
  TOUCH_ID: 'TOUCH_ID',

  CUSTOM_NAV_BAR: 'CUSTOM_NAV_BAR',

  WEB_WINDOW: 'WEB_WINDOW',

  ACTION_SCREEN: 'ACTION_SCREEN',

  // --------------------------------- GROW SCREENS ---------------------------------

  GROW_HOMEPAGE: 'GROW_HOMEPAGE',

  ARTICLE: 'ARTICLE',

  // --------------------------------- SETTINGS SCREENS ---------------------------------

  // settings homepage
  SETTINGS_PANEL: 'SETTINGS_PANEL',

  // user profile view
  PROFILE: 'PROFILE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',

  RECURRING_DETAIL: 'RECURRING_DETAIL',

  INVESTOR_QUESTIONS: 'INVESTOR_QUESTIONS',

  FAQ: 'FAQ',

  ABOUT_US: 'ABOUT_US',

  DOCUMENTS: 'DOCUMENTS',

  VIEW_TRANSFERS: 'VIEW_TRANSFERS',

  SHOW_CONFIG: 'SHOW_CONFIG',

  EDIT_PROFILE: 'EDIT_PROFILE',

  BANK_SETUP: 'BANK_SETUP',

  STATEMENTS: 'STATEMENTS',

  CONFIRMATIONS: 'CONFIRMATIONS',

  REGULAR_TRANSFERS: 'REGULAR_TRANSFERS',

  ACTIVITY: 'ACTIVITY',

  BROKER_DEALER_PAGE: 'BROKER_DEALER_PAGE',

  CHILD_INFO_PAGE: 'CHILD_INFO_PAGE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',

  CONNECT_BANK: 'CONNECT_BANK',

  SELECT_ACCOUNT_TYPE: 'SELECT_ACCOUNT_TYPE',

  ADD_ROUTING_NUMBER: 'ADD_ROUTING_NUMBER',

  ADD_ACCOUNT_INFORMATION: 'ADD_ACCOUNT_INFORMATION',

  BANK_VERIFICATION_1: 'BANK_VERIFICATION_1',

  BANK_VERIFICATION_2: 'BANK_VERIFICATION_2',

  BANK_ACCOUNT_PENDING: 'BANK_ACCOUNT_PENDING',

  DEBUG_LOG: 'DEBUG_LOG',

  SETTING: 'SETTING',

  ABOUT_SETTING: 'ABOUT_SETTING',

  ACTIVITY_SETTING: 'ACTIVITY_SETTING',

  BANK_SETTING: 'BANK_SETTING',

  BANK_DISCONNECT_NOTIFICATION: 'BANK_DISCONNECT_NOTIFICATION',

  RESET_BANK_ACCOUNT: 'RESET_BANK_ACCOUNT',

  DOCUMENTS_SETTING: 'DOCUMENTS_SETTING',

  EDIT_PROFILE_SETTING: 'EDIT_PROFILE_SETTING',

  FAQ_SETTING: 'FAQ_SETTING',

  REFER_A_FRIEND: 'REFER_A_FRIEND',
  // --------------------------------- CHILD SCREENS ---------------------------------

  // Child Homescreen container
  CHILD_HOMEPAGE_CONTAINER_SCREEN: 'CHILD_HOMEPAGE_CONTAINER_SCREEN',

  // CHILD HOMESCREEN
  CHILD_HOMEPAGE_SCREEN  : 'CHILD_HOMEPAGE_SCREEN',

  // child portfolio screen
  CHILD_PORTFOLIO_SCREEN   : 'CHILD_PORTFOLIO_SCREEN',

  // Add Child screen
  ADD_CHILD_SCREEN     : 'ADD_CHILD_SCREEN',

  // Add Child Birth Date screen
  ADD_CHILD_BIRTH_DATE     : 'ADD_CHILD_BIRTH_DATE',

  // child's ssn screen
  CHILD_SSN_SCREEN     : 'CHILD_SSN_SCREEN',

  // child view screen
  CHILD_VIEW_SCREEN     : 'CHILD_VIEW_SCREEN',

  CREATE_CHILD_NOTIFICATION: 'CREATE_CHILD_NOTIFICATION',

  CHILD_AGE_LIMITATION: 'CHILD_AGE_LIMITATION',

  SSN_CONFIRM: 'SSN_CONFIRM',

  SSN_POPUP: 'SSN_POPUP',

  USER_SSN: 'USER_SSN',

  SSN_REQUEST_CONTACT: 'SSN_REQUEST_CONTACT',

  CHILD_INVESTING: 'CHILD_INVESTING',

  // --------------------------------- INVEST SCREENS ----------------------------------

  INVEST_HOMEPAGE: 'INVESTMENT_HOMEPAGE',

  ADD_INVESTMENT: 'ADD_INVESTMENT',

  INVEST_AMOUNT: 'INVEST_AMOUNT',

  INVEST_FREQUENCY: 'INVEST_FREQUENCY',

  LI_SELECT_INVESTMENT: 'LI_SELECT_INVESTMENT',

  LI_SHOW_INVESTMENT_DETAIL: 'LI_SHOW_INVESTMENT_DETAIL',

  LI_SHOW_INVESTMENT_FUND: 'LI_SHOW_INVESTMENT_FUND',

  LI_SELL: 'LI_SELL',

  LI_BUY: 'LI_BUY',

  LI_EDIT_RECURRING: 'LI_EDIT_RECURRING',

  LI_EDIT_GOAL: 'LI_EDIT_GOAL',

  LI_CONFIRM: 'LI_CONFIRM',

  // --------------------------------- GOAL SCREENS ----------------------------------

  // select type of goal
  SELECT_GOAL_SCREEN   : 'SELECT_GOAL_SCREEN',

  // add goal
  ADD_GOAL_SCREEN      : 'ADD_GOAL_SCREEN',

  NAVIGATE_TO_EDIT_GOAL : 'NAVIGATE_TO_EDIT_GOAL',

  // duration of the goal
  GOAL_DURATION_SCREEN : 'GOAL_DURATION_SCREEN',

  GOAL_DURATION_SELECTION_SCREEN: 'GOAL_DURATION_SELECTION_SCREEN',

  // select risk for the goal
  SELECT_RISK_SCREEN   : 'SELECT_RISK_SCREEN',

  // select goal amount
  GOAL_AMOUNT_SCREEN   : 'GOAL_AMOUNT_SCREEN',

  // cost expected
  COST_EXPECTED: 'COST_EXPECTED',

  // disclaimer
  DISCLAIMER: 'DISCLAIMER',

  // select recurring amount
  RECURRING_AMOUNT_SCREEN : 'RECURRING_AMOUNT_SCREEN',

  INVEST: 'INVEST',

  GOAL_HOMEPAGE_SCREEN: 'GOAL_HOMEPAGE_SCREEN',

  PORTFOLIO_DETAIL: 'PORTFOLIO_DETAIL',

  INVEST_READY: 'INVEST_READY',

  SKIP_CONFIRM: 'SKIP_CONFIRM',

  INVEST_UNDERWAY: 'INVEST_UNDERWAY',

  WITHDRAW: 'WITHDRAW',

  EDIT_RECURRING_AMOUNT: 'EDIT_RECURRING_AMOUNT',

  RISK_NOTIFICATION: 'RISK_NOTIFICATION',

  GOAL_BASE: 'GOAL_BASE',

  // --
  LI_SELECT_GOAL: 'LI_SELECT_GOAL',
  LI_GOAL_DETAIL: 'LI_GOAL_DETAIL',
  LI_SELECT_GOAL_AMOUNT: 'LI_SELECT_GOAL_AMOUNT',
  LI_SELECT_GOAL_DURATION: 'LI_SELECT_GOAL_AGE',
  LI_SELECT_GOAL_PORTFOLIO: 'LI_SELECT_GOAL_PORTFOLIO',
  LI_SELECT_GOAL_FUND: 'LI_SELECT_GOAL_FUND',
  LI_CONFIRM_GOAL: 'LI_CONFIRM_GOAL',
  LI_START_INVESTING: 'LI_START_INVESTING',
  LI_PREPARE_INVESTMENT: 'LI_PREPARE_INVESTMENT',

  // --------------------------------- USER Screens ----------------------------------
  USER_INPUT_DETAIL_1: 'USER_INPUT_DETAIL_1',
  USER_INPUT_DETAIL_2: 'USER_INPUT_DETAIL_2',
  USER_INPUT_DETAIL_3: 'USER_INPUT_DETAIL_3',
  USER_INPUT_MANUAL_ADDRESS: 'USER_INPUT_MANUAL_ADDRESS',
  USER_INPUT_DETAIL_4: 'USER_INPUT_DETAIL_4',
  USER_INPUT_DETAIL_5: 'USER_INPUT_DETAIL_5',
  USER_INPUT_DETAIL_6: 'USER_INPUT_DETAIL_6',
  USER_INPUT_DETAIL_7: 'USER_INPUT_DETAIL_7',
  USER_INPUT_DETAIL_8: 'USER_INPUT_DETAIL_8',
  USER_INPUT_DETAIL_9: 'USER_INPUT_DETAIL_9',
  USER_INPUT_DETAIL_SSN: 'USER_INPUT_DETAIL_SSN',
  USER_INPUT_PHONE_NUMBER: 'USER_INPUT_PHONE_NUMBER',
  ACCEPT_TERMS_CONDITIONS: 'ACCEPT_TERMS_CONDITIONS',
  USER_COUNTRY_BORN: 'USER_COUNTRY_BORN',
  USER_COUNTRY_CITIZENSHIP: 'USER_COUNTRY_CITIZENSHIP',
  USER_VISA_TYPE: 'USER_VISA_TYPE',
  USER_VISA_EXPIRY: 'USER_VISA_EXPIRY',
  OTHER_RESIDENCE: 'OTHER_RESIDENCE',
  CONFIRM_PUSH_NOTIFICATION: 'CONFIRM_PUSH_NOTIFICATION',
  AGE_LIMITATION_NOTIFICATION: 'AGE_LIMITATION_NOTIFICATION',
  PARENT_DASHBOARD: 'PARENT_DASHBOARD',
  IDENTITY_VERIFICATION: 'IDENTITY_VERIFICATION',
  CONFIRM_INVESTOR_PROFILE: 'CONFIRM_INVESTOR_PROFILE',
  USER_SSN_POPUP: 'USER_SSN_POPUP',

  PLAID_CONNECT: 'PLAID_CONNECT',

  // --------------------------------- CHAT Screens ----------------------------------

  CHAT_ROOM: 'CHAT_ROOM'
}

export const LW_SCREEN = {

  // onboarding screens
  ONBOARD_SCREEN_1: '[ONBOARDING] User Detail',
  ONBOARD_SCREEN_D0B: '[ONBOARDING] User Date of Birth',
  ONBOARD_SCREEN_2: '[ONBOARDING] User Address',
  ONBOARD_SCREEN_3: '[ONBOARDING] User Residence Type',
  ONBOARD_SCREEN_4: '[ONBOARDING] User SSN',
  ONBOARD_SCREEN_5: '[ONBOARDING] User Country Born',
  ONBOARD_SCREEN_6: '[ONBOARDING] User Country Citizenship',
  ONBOARD_SCREEN_7: '[ONBOARDING] User Visa Type',
  ONBOARD_SCREEN_8: '[ONBOARDING] User Visa Expiry',
  ONBOARD_SCREEN_9: '[ONBOARDING] User Employment Type',
  ONBOARD_SCREEN_10: '[ONBOARDING] User Annual Income',
  ONBOARD_SCREEN_11: '[ONBOARDING] User Total Assets',
  ONBOARD_SCREEN_12: '[ONBOARDING] User Investor Type',
  ONBOARD_SCREEN_13: '[ONBOARDING] User Declaration',
  ONBOARD_PROGRAM_AGREEMENT: '[ONBOARDING] Program Agreement',

  // child screens
  ADD_CHILD: '[CHILD_LOOP] Add Child Screen',
  ADD_CHILD_CONFIRM_SSN: '[CHILD_LOOP] Confirm SSN',
  ADD_CHILD_SUBMIT_SSN: '[CHILD_LOOP] Submit SSN',

  // goal loop
  GOAL_LOOP_SELECT_INVESTMENT: '[GOAL_LOOP] Select investment',
  GOAL_LOOP_SELECT_AMOUNT: '[GOAL_LOOP] Select Amount',
  GOAL_LOOP_INVEST_READY: '[GOAL_LOOP] Invest Ready Screen',
  GOAL_LOOP_PLAID: '[GOAL_LOOP] Plaid Screen',
  GOAL_LOOP_TRANSFER_UNDERWAY: '[GOAL_LOOP] Transfer underway',

  // setting screens
  PUSH_NOTIFICATION: '[SETTING] Push Notificatin',
  PASSCODE: '[SETTING] Passcode'

}

export const LW_EVENTS = {

  // user signup
  USER_SIGNUP_COGNITO_SUCCESS: '[USER SIGNUP] Cognito Success',

  // user login loop
  USER_LOGIN_COGNITO_SUCCESS: '[USER LOGIN] Cognito Success',
  USER_LOGIN_USER_FETCH_SUCCESS: '[USER LOGIN] User Fetch Success',

  // detail fetch success
  USER_DETAIL_FETCH_SUCCESS: '[DASHBOARD] user detail fetch SUCCESS',
  USER_DETAIL_FETCH_FAILURE: '[DASHBOARD] user detail fetch FAILURE',

  // onboarding
  PROGRAM_AGREEMENT_ACCEPTED: '[ONBOARDING] Program Agreement Accepted',

  // child loop
  CHILD_LOOP_ADD_CHILD_SENDING_REQUEST: '[CHILD_LOOP] sending request',
  CHILD_LOOP_ADD_CHILD_ERROR: '[CHILD_LOOP] add child error',
  CHILD_LOOP_ADD_CHILD_SUCCESS: '[CHILD_LOOP] add child success',
  CHILD_LOOP_TPT_SUCCESS: '[CHILD_LOOP] tpt account created',
  CHILD_LOOP_TPT_FAILURE: '[CHILD_LOOP] tpt account failure',

  // goal loop
  GOAL_LOOP_SKIP: '[GOAL_LOOP] Skipping goal creation',
  GOAL_LOOP_ADDING_GOAL: '[GOAL_LOOP] Sending request',
  GOAL_LOOP_ADD_SUCCESS: '[GOAL_LOOP] Success',
  GOAL_LOOP_ADD_FAILURE: '[GOAL_LOOP] Failure',
  GOAL_LOOP_LAUNCHING_PLAID: '[GOAL_LOOP] Confirm Plaid Launch',
  GOAL_LOOP_SKIPPING_PLAID: '[GOAL_LOOP] Plaid - Skip Chosen',
  GOAL_LOOP_PLAID_SUCCESS: '[GOAL_LOOP] Plaid - Success',
  GOAL_LOOP_PLAID_EXIT: '[GOAL_LOOP] Plaid - Exit',
  GOAL_LOOP_FUNDING_SUCCESS: '[GOAL_LOOP] Funding - success',
  GOAL_LOOP_FUNDING_FAILURE: '[GOAL_LOOP] Funding - failure',
  GOAL_LOOP_TRANSFER_UNDERWAY: '[GOAL_LOOP] Transfer - sending request',
  GOAL_LOOP_TRANSFER_SUCCESS: '[GOAL_LOOP] Transfer - success',
  GOAL_LOOP_TRANSFER_FAILURE: '[GOAL_LOOP] Transfer - failure',

  // settings loop
  PUSH_NOTIFICATION_CONFIRMED: '[SETTINGS] Push notification confirmed'
}

export const LW_EVENT_TYPE = {
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  ONBOARDING: 'OnBoarding',
  CHILD_LOOP: 'Child Loop',
  GOAL_LOOP: 'Goal Loop',
  DASHBOARD: 'Dashboard',
  SETTINGS: 'Settings'
}
