#!/bin/bash
if [ $# == 3 ]; then
    sed -i '' 's/.*export const CURRENT_VERSION =.*$/export const CURRENT_VERSION = '"'""$3""'"'/' $1
    case $2 in
        0)
            sed -i '' 's/.*export const CURRENT_ENVIRONMENT =.*$/export const CURRENT_ENVIRONMENT = ENVIRONMENT.UAT1/' $1
        ;;
        1)
            sed -i '' 's/.*export const CURRENT_ENVIRONMENT =.*$/export const CURRENT_ENVIRONMENT = ENVIRONMENT.UAT2/' $1
        ;;
        2)
            sed -i '' 's/.*export const CURRENT_ENVIRONMENT =.*$/export const CURRENT_ENVIRONMENT = ENVIRONMENT.PROD/' $1
        ;;
    esac
else
    echo "You need to pass AppConfig.js path as a parameter"
fi
