/* eslint-disable key-spacing,key-spacing,no-trailing-spaces,no-undef */
/**
 * Created by viktor on 7/6/17.
 */

// ========================================================
// Import Entities
// ========================================================

import { GOAL_ENTITIES } from '../Utility/Mapper/Goal'
import { INVESTMENT_ENTITIES } from '../Utility/Mapper/Investment'
import { CHILD_ENTITIES } from '../Utility/Mapper/Child'
import { AUTH_ENTITIES } from '../Utility/Mapper/Auth'
import { USER_ENTITIES } from '../Utility/Mapper/User'
import { LEARN_ENTITIES } from '../Utility/Mapper/Learn'
import { SPROUT } from '../Utility/Mapper/Screens'
import { COMMON_ENTITIES } from '../Utility/Mapper/Common'
import { SETTINGS_ENTITIES } from '../Utility/Mapper/Settings'
import { ONBOARDING_ENTITIES } from '../Utility/Mapper/Onboard'

// ========================================================
// Export parameters
// ========================================================

export default {

  // ------------ lean module parameters ------------

  FETCH_LEARN_MODULES_SUCCESS: [LEARN_ENTITIES.CONTENT],

  // ------------ investment parameters ------------

  ADD_NEW_INVESTMENT: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],

  SHOW_INVESTMENT: [CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.INVESTMENT_ID, COMMON_ENTITIES.NAVIGATOR],
  ADD_INVESTMENT: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.INVESTMENT_NAME, INVESTMENT_ENTITIES.INVESTMENT_RISK_ID, INVESTMENT_ENTITIES.INVESTMENT_PATH_ID, INVESTMENT_ENTITIES.INVESTMENT_AMOUNT, INVESTMENT_ENTITIES.INVESTMENT_FREQUENCY, USER_ENTITIES.IS_PLAID_LINKED, COMMON_ENTITIES.NAVIGATOR],
  ADD_INVESTMENT_SUCCESS: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.INVESTMENT_ID, INVESTMENT_ENTITIES.INVESTMENT_DATA],
  ADD_INVESTMENT_FAILURE: ['error'],

  INVESTMENT_CONFIRM: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, INVESTMENT_ENTITIES.INVESTMENT_NAME, INVESTMENT_ENTITIES.INVESTMENT_AMOUNT, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, GOAL_ENTITIES.IS_WITHDRAW, 'tickerName', COMMON_ENTITIES.NAVIGATOR],

  FETCH_PRODUCTS: [],
  FETCH_PRODUCTS_SUCCESS: [INVESTMENT_ENTITIES.PRODUCTS, INVESTMENT_ENTITIES.TYPES],
  FETCH_PRODUCTS_FAILURE: ['error'],

  BUY_INVESTMENT: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  SELL_INVESTMENT: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  INVESTMENT_COMPLETED: [COMMON_ENTITIES.NAVIGATOR, 'IS_MODEL'],

  INVESTMENT_SELECTED: [CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.PRODUCT, COMMON_ENTITIES.NAVIGATOR, INVESTMENT_ENTITIES.IS_DISPLAY_ONLY, INVESTMENT_ENTITIES.INVESTMENT_INTERNAL_ID, INVESTMENT_ENTITIES.INVESTMENT_ID, INVESTMENT_ENTITIES.INVESTMENT_AMOUNT, INVESTMENT_ENTITIES.INVESTMENT_RECURRING_AMOUNT, INVESTMENT_ENTITIES.IS_RECURRENCE_INVESTMENT_EXIST],
  SELECT_INVESTMENT_AMOUNT: [CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.INVESTMENT_NAME, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.IS_ADD_RECURRING, INVESTMENT_ENTITIES.PRODUCT],
  INVESTMENT_AMOUNT_SELECTED: [CHILD_ENTITIES.CHILD_ID, INVESTMENT_ENTITIES.INVESTMENT_NAME, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.IS_ADD_RECURRING, INVESTMENT_ENTITIES.PRODUCT],

  SELECT_INVESTMENT: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  SHOW_INVESTMENT_DETAIL: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  SHOW_INVESTMENT_FUND: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.GID],

  // ------------ goal parameters ------------

  ADD_CUSTOM_GOAL : [GOAL_ENTITIES.USER_ID, GOAL_ENTITIES.CID, GOAL_ENTITIES.NAME, CHILD_ENTITIES.FIRST_NAME, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.RISK_SELECTED],
  ADD_CUSTOM_GOAL_SUCCESS : [GOAL_ENTITIES.CID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE, USER_ENTITIES.USER_ID, GOAL_ENTITIES.RISK_SELECTED],
  ADD_CUSTOM_GOAL_FAILURE : ['error'],

  GOAL_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR],

  SKIP_GOAL: [COMMON_ENTITIES.NAVIGATOR],
  MAKE_GOAL : [GOAL_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.PORTFOLIO_RISK, GOAL_ENTITIES.DURATION, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, USER_ENTITIES.IS_PLAID_LINKED, COMMON_ENTITIES.NAVIGATOR],
  ADD_GOAL_SUCCESS: [GOAL_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_DATA],
  ADD_GOAL_FAILURE: ['error'],

  NOTIFY_RISK_ASSESSMENT: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.PORTFOLIO_RISK, GOAL_ENTITIES.DURATION, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, USER_ENTITIES.IS_PLAID_LINKED, GOAL_ENTITIES.SUGGESTED_RISK, COMMON_ENTITIES.NAVIGATOR],

  CUSTOMIZE_PORTFOLIO: [COMMON_ENTITIES.NAVIGATOR],

  GOAL_TYPE_SELECTED: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  GOAL_DURATION_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  GOAL_DURATION_SELECTION_NEEDED: [GOAL_ENTITIES.GOAL_DURATION_TYPE, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR_TITLE, COMMON_ENTITIES.NAVIGATOR],
  SELECT_RISK: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  COST_EXPECTED_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR_TITLE, COMMON_ENTITIES.NAVIGATOR],
  ADD_RISK: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  HIDE_RISK: [COMMON_ENTITIES.NAVIGATOR],
  GOAL_AMOUNT_SELECTED: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.NAVIGATOR_TITLE],
  SHOW_INVEST: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.IS_STALE],
  HIDE_INVEST: [COMMON_ENTITIES.NAVIGATOR],

  UPDATE_COMPLETE_GOAL: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.IS_RECURRING, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, GOAL_ENTITIES.FIRST_TRANSFER_DATE, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_PARTIAL_GOAL: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_AMOUNT, GOAL_ENTITIES.PORTFOLIO_RISK, GOAL_ENTITIES.DURATION, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_GOAL_SUCCESS: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.GOAL_DATA, COMMON_ENTITIES.NAVIGATOR],
  UPDATE_GOAL_FAILURE: ['error'],

  NAVIGATE_TO_EDIT_GOAL: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  EDIT_GOAL: [USER_ENTITIES.USER_ID, GOAL_ENTITIES.GID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.GOAL_AMOUNT, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_WITHDRAW: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, CHILD_ENTITIES.FIRST_NAME, GOAL_ENTITIES.NAME, GOAL_ENTITIES.BALANCE, COMMON_ENTITIES.NAVIGATOR],
  WITHDRAW: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.WITHDRAW_AMOUNT, COMMON_ENTITIES.NAVIGATOR],
  WITHDRAW_SUCCESS: [GOAL_ENTITIES.INSTRUCTION_DATA, COMMON_ENTITIES.NAVIGATOR],
  WITHDRAW_FAILURE: ['error', COMMON_ENTITIES.NAVIGATOR],

  INVEST_ON_GOAL: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_HOMEPAGE: [COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.CHILD_ID, USER_ENTITIES.SHOULD_REFRESH],

  NAVIGATE_TO_ACTION_SCREEN: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_TRANSFER_SCREEN: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.RECURRING_AMOUNT, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.SHOW_BANK_LINKED],
  TRANSFER: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY, GOAL_ENTITIES.ONE_OFF_INVESTMENT, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR],
  TRANSFER_SUCCESS: [GOAL_ENTITIES.INSTRUCTION_DATA],
  TRANSFER_FAILURE: ['error'],

  NAVIGATE_TO_EDIT_RECURRING_AMOUNT: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],

  FETCH_PERFORMANCE_DATA: [AUTH_ENTITIES.ID_TOKEN, GOAL_ENTITIES.TICKER_NAME],
  FETCH_PERFORMANCE_DATA_SUCCESS: [GOAL_ENTITIES.PERFORMANCE_DATA],
  FETCH_PERFORMANCE_DATA_FAILURE: ['error'],

  FETCH_INVEST_CHART_DATA: [USER_ENTITIES.EMAIL_ID, GOAL_ENTITIES.TICKER_NAME],
  FETCH_INVEST_CHART_DATA_SUCCESS: [GOAL_ENTITIES.INVEST_CHART_DATA, GOAL_ENTITIES.TICKER_NAME],
  FETCH_INVEST_CHART_DATA_FAILURE: ['error'],
  FLUSH_INVEST_CHART_DATA: [GOAL_ENTITIES.TICKER_NAME],

  FETCH_GOAL_DETAIL: [USER_ENTITIES.USER_ID, GOAL_ENTITIES.GID],
  FETCH_GOAL_DETAIL_SUCCESS: [GOAL_ENTITIES.GOAL_DATA],
  FETCH_GOAL_DETAIL_FAILURE: ['error'],

  FETCH_GOAL_CHART_DATA: [GOAL_ENTITIES.GID],
  FETCH_GOAL_CHART_DATA_SUCCESS: [GOAL_ENTITIES.GID, GOAL_ENTITIES.CHART_DATA],
  FETCH_GOAL_CHART_DATA_FAILURE: ['error'],

  CONFIRM_BANK_CONNECTION: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, GOAL_ENTITIES.RECURRING_AMOUNT, COMMON_ENTITIES.NAVIGATOR, GOAL_ENTITIES.INSTRUCTION_NEXT_TRANSFER_DATE],
  SKIP_BANK_CONNECTION: [COMMON_ENTITIES.NAVIGATOR],
  POP_SCREEN: [COMMON_ENTITIES.NAVIGATOR],

  SHOW_DISCLAIMER: [COMMON_ENTITIES.NAVIGATOR],

  SELECT_GOAL: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],

  CONFIRM_GOAL: [INVESTMENT_ENTITIES.IS_INVESTMENT, GOAL_ENTITIES.GOAL_DATA, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_DEBUG_WINDOW: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_DASHBOARD: [COMMON_ENTITIES.NAVIGATOR],

  // ------------ child parameters ------------
  ADD_AVATAR: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.AVATAR],

  SHOW_CHILD: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  POP_CHILD_VIEW: [COMMON_ENTITIES.NAVIGATOR],

  ASK_SSN: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GOAL_DATA, INVESTMENT_ENTITIES.IS_INVESTMENT, COMMON_ENTITIES.NAVIGATOR],

  ADD_CHILD: [CHILD_ENTITIES.USER_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB, CHILD_ENTITIES.SSN, USER_ENTITIES.EMAIL_ID, COMMON_ENTITIES.NAVIGATOR, SETTINGS_ENTITIES.IMAGE_METADATA, AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.DISPATCH, CHILD_ENTITIES.IS_ADDING_DREAM, CHILD_ENTITIES.IS_ADDING_DESIRE, USER_ENTITIES.SSN, USER_ENTITIES.IS_SSN_ADDED, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  ADD_CHILD_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.USER_ID, CHILD_ENTITIES.IS_ADDING_DREAM, CHILD_ENTITIES.IS_ADDING_DESIRE, USER_ENTITIES.IS_SSN_ADDED, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  ADD_CHILD_FAILURE: ['error'],

  CREATE_CHILD_ACCOUNT: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, USER_ENTITIES.SSN, CHILD_ENTITIES.SSN, GOAL_ENTITIES.GOAL_DATA, INVESTMENT_ENTITIES.IS_INVESTMENT, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.P_FUNC],
  CREATE_CHILD_ACCOUNT_SUCCESS: [CHILD_ENTITIES.CHILD_ID],
  CREATE_CHILD_ACCOUNT_FAILURE: ['error'],

  FETCH_CHILDREN_DETAILS: [CHILD_ENTITIES.CHILD_IDs],
  FETCH_CHILDREN_DETAILS_SUCCESS: [],
  FETCH_CHILDREN_DETAILS_FAILURE: [],

  FETCH_CHILD_CHART_DATA: [CHILD_ENTITIES.CHILD_ID],
  FETCH_CHILD_CHART_DATA_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.CHART_DATA],
  FETCH_CHILD_CHART_DATA_FAILURE: ['error'],

  SUBMIT_CHILD_SSN: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, COMMON_ENTITIES.NAVIGATOR],

  SUBMIT_CHILD_ACCOUNT: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, USER_ENTITIES.SSN, CHILD_ENTITIES.SSN, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.IS_ADDING_DESIRE, CHILD_ENTITIES.IS_ADDING_DREAM, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  SUBMIT_CHILD_ACCOUNT_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.IS_ADDING_DREAM, CHILD_ENTITIES.IS_ADDING_DESIRE, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  SUBMIT_CHILD_ACCOUNT_FAILURE: ['error'],

  FETCH_STOCK_PERFORMANCE: [CHILD_ENTITIES.CHILD_ID, USER_ENTITIES.USER_ID, AUTH_ENTITIES.EMAIL, SETTINGS_ENTITIES.IMAGE_TYPE],
  FETCH_STOCK_PERFORMANCE_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.STOCK_PERFORMANCE_DATA],
  FETCH_STOCK_PERFORMANCE_FAILURE: ['error'],

  SET_CHILD_SSN_ADDED: [CHILD_ENTITIES.CHILD_ID],

  ADD_NEW_GOAL: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],
  ADD_NEW_CHILD: [COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.IS_ADDING_DREAM, CHILD_ENTITIES.IS_ADDING_DESIRE, CHILD_ENTITIES.SHOULD_UPDATE_ONBOARDING, COMMON_ENTITIES.IS_ONBOARDING_FLOW],

  NAVIGATE_TO_ADD_CHILD: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.RESET_STACK],
  NAVIGATE_TO_CHILD_SSN: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.IS_ADDING_DREAM, CHILD_ENTITIES.IS_ADDING_DESIRE],

  SHOW_GOAL: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.NAME, COMMON_ENTITIES.NAVIGATOR],
  HIDE_GOAL: [COMMON_ENTITIES.NAVIGATOR],

  NOTIFY_AGE_LIMITATION: [COMMON_ENTITIES.NAVIGATOR],

  SHOW_BROKER_DEALER_CHILD_INFO: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.BD_ACCOUNT_ID, COMMON_ENTITIES.NAVIGATOR],
  SHOW_BROKER_DEALER_CHILD_INFO_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.BROKER_DEALER_DATA],
  SHOW_BROKER_DEALER_CHILD_INFO_FAILURE: ['error'],

  // ------------ auth parameters ------------
  NAVIGATE_AUTH: [AUTH_ENTITIES.AUTH_TYPE, COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.EMAIL],

  // login user
  LOGIN:  [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH, AUTH_ENTITIES.HELPING_SIGNUP, AUTH_ENTITIES.IS_PASSCODE_LOGIN, 'uid'],
  // login user success
  LOGIN_SUCCESS: [AUTH_ENTITIES.ID_TOKEN, AUTH_ENTITIES.PIN, COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.IS_PASSCODE_LOGIN],
  // LOGIN_SUCCESS: (to be added later )
  LOGIN_FAILURE: ['error'],

  LOGOUT : [COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.IS_PASSCODE_LOGOUT],

  PROMPT_AUTH: [COMMON_ENTITIES.NAVIGATOR],

  PASSCODE_LOGIN: [USER_ENTITIES.EMAIL_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  PASSCODE_LOGIN_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],

  SIGNUP: [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, COMMON_ENTITIES.NAVIGATOR, 'uid', COMMON_ENTITIES.DISPATCH],
  SIGNUP_SUCCESS : [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.EMAIL_ID, AUTH_ENTITIES.ID_TOKEN],
  SIGNUP_FAILURE : ['error'],

  SHOW_TOUCH_ID: [COMMON_ENTITIES.NAVIGATOR],
  HIDE_TOUCH_ID: [COMMON_ENTITIES.NAVIGATOR],

  FETCH_PIN_SUCCESS: [AUTH_ENTITIES.PIN],
  FETCH_PIN_FAILURE: ['error'],

  REGISTER_PIN: [AUTH_ENTITIES.PIN, USER_ENTITIES.EMAIL_ID, AUTH_ENTITIES.PIN_ACTION_TYPE, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH, AUTH_ENTITIES.GO_TO_HOMEPAGE],
  REGISTER_PIN_SUCCESS: [AUTH_ENTITIES.PIN_ACTION_TYPE, COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.PIN, AUTH_ENTITIES.GO_TO_HOMEPAGE],
  REGISTER_PIN_FAILURE: ['error'],

  // ------------ user parameters ------------
  FETCH_USER: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  FETCH_USER_SUCCESS: [USER_ENTITIES.USER_ID, USER_ENTITIES.USER_DATA, USER_ENTITIES.TODO_LIST],
  FETCH_USER_FAILURE: ['error'],

  FETCH_USER_DETAIL: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR],
  FETCH_USER_DETAIL_SUCCESS: [USER_ENTITIES.USER_ID, USER_ENTITIES.USER_DETAIL],
  FETCH_USER_DETAIL_FAILURE: ['error', COMMON_ENTITIES.NAVIGATOR],

  FETCH_USER_INSTRUCTIONS: [USER_ENTITIES.USER_ID],
  FETCH_USER_INSTRUCTIONS_SUCCESS: [USER_ENTITIES.USER_DATA],
  FETCH_USER_INSTRUCTIONS_FAILURE: ['error'],

  MODIFY_USER_INSTRUCTION: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.INSTRUCTION_ID, GOAL_ENTITIES.INSTRUCTION_ACTION, COMMON_ENTITIES.NAVIGATOR],
  MODIFY_USER_INSTRUCTION_SUCCESS: [GOAL_ENTITIES.INSTRUCTION_DATA],
  MODIFY_USER_INSTRUCTION_FAILURE: ['error'],

  MODIFY_USER_RECURRING_INSTRUCTION: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.INSTRUCTION_ID, GOAL_ENTITIES.RECURRING_AMOUNT, GOAL_ENTITIES.RECURRING_FREQUENCY],
  MODIFY_USER_RECURRING_INSTRUCTION_SUCCESS: [GOAL_ENTITIES.INSTRUCTION_DATA],
  MODIFY_USER_RECURRING_INSTRUCTION_FAILURE: ['error'],

  SET_USER_ID: [USER_ENTITIES.USER_ID, USER_ENTITIES.EMAIL_ID],
  SET_USERNAME: [USER_ENTITIES.EMAIL_ID],
  SET_FIRST_NAME: [USER_ENTITIES.FIRST_NAME],
  SET_LAST_NAME: [USER_ENTITIES.LAST_NAME],
  NAVIGATE_USER_DETAIL_INPUT: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.RESIDENCY_TYPE, COMMON_ENTITIES.CAN_POP],
  IDENTITY_CHECK_COMPLETE: [USER_ENTITIES.IDENTITY_DATA, COMMON_ENTITIES.NAVIGATOR],
  RESTORE_IDENTITY_DATA: [USER_ENTITIES.IDENTITY_DATA],
  SET_PASSCODE: [COMMON_ENTITIES.NAVIGATOR, AUTH_ENTITIES.PIN_ACTION_TYPE, AUTH_ENTITIES.GO_TO_HOMEPAGE],

  SELECT_BANK_ACCOUNT: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TODO: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_AGREEMENT: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_AMOUNT_VERIFICATION_SCREEN: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],

  STORE_USER_SSN: [USER_ENTITIES.USER_ID, USER_ENTITIES.SSN, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.MARK_REQUEST_SSN, CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.SSN_REQUEST_PHONE_NUMBER, CHILD_ENTITIES.UNIQUE_CODE, USER_ENTITIES.EMAIL_ID, CHILD_ENTITIES.UNIQUE_URL, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  STORE_USER_SSN_SUCCESS: [COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  STORE_USER_SSN_FAILURE: ['error'],

  STORE_USER_ADDRESS: [USER_ENTITIES.USER_ID, USER_ENTITIES.IDENTITY_DATA],

  MARK_SSN_REQUEST: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.MARK_REQUEST_SSN, CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.SSN_REQUEST_PHONE_NUMBER, CHILD_ENTITIES.UNIQUE_CODE, USER_ENTITIES.EMAIL_ID, CHILD_ENTITIES.UNIQUE_URL, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  MARK_SSN_REQUEST_SUCCESS: [COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.IS_ONBOARDING_FLOW],
  MARK_SSN_REQUEST_FAILURE: ['error'],

  OPEN_ARTICLE: [LEARN_ENTITIES.MODULE, COMMON_ENTITIES.NAVIGATOR],
  CLOSE_ARTICLE: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TC: [COMMON_ENTITIES.NAVIGATOR],
  AGREE_TC: [COMMON_ENTITIES.NAVIGATOR],
  DISAGREE_TC: [COMMON_ENTITIES.NAVIGATOR],
  DISMISS_ALL_MODEL: [COMMON_ENTITIES.NAVIGATOR],

  QUERY_ACCOUNT_API: [USER_ENTITIES.USER_ID, USER_ENTITIES.ACCOUNT_ID, COMMON_ENTITIES.NAVIGATOR],
  QUERY_ACCOUNT_API_SUCCESS: [USER_ENTITIES.USER_DATA],
  QUERY_ACCOUNT_API_FAILURE: ['error'],

  NAVIGATE_TO_CONNECT_BANK: [COMMON_ENTITIES.NAVIGATOR],
  CONNECT_BANK: [],
  CONNECT_BANK_SUCCESS: [],
  CONNECT_BANK_FAILURE: [],

  SWITCH_ON_DEBUG_MODE: [USER_ENTITIES.USER_ID],
  SWITCH_ON_DEBUG_MODE_SUCCESS: [USER_ENTITIES.USER_DETAIL],

  FETCH_GLOSSARY: [],
  FETCH_GLOSSARY_SUCCESS: [USER_ENTITIES.GLOSSARY],
  FETCH_GLOSSARY_FAILURE: ['error'],

  SET_NAV_TAB: [USER_ENTITIES.TAB, USER_ENTITIES.TAB_IS_GOAL],

  // ------------ onboarding parameters ------------

  ONBOARDING_STARTED: [USER_ENTITIES.EMAIL_ID],
  ONBOARDING_COMPLETED: [USER_ENTITIES.EMAIL_ID],
  UPDATE_CURRENT_ONBOARDING: [USER_ENTITIES.EMAIL_ID, SPROUT.SCREEN_TYPE, COMMON_ENTITIES.PROPS],

  MARK_CURRENT_ONBOARDING_SCREEN: [USER_ENTITIES.USER_ID, ONBOARDING_ENTITIES.CURRENT_PROFILE_SCREEN],
  MARK_PROFILE_COMPLETION: [USER_ENTITIES.USER_ID],
  PROGRAM_ACCEPTED: [USER_ENTITIES.USER_ID, ONBOARDING_ENTITIES.PROFILE_DATA, COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.EMAIL_ID],

  // ------------ Common parameters ------------
  DISABLE_ERROR: [AUTH_ENTITIES.SHOW_ERROR],

  INITIATE_PLAID: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.NAVIGATOR],
  DISMISS_PLAID: [COMMON_ENTITIES.NAVIGATOR],
  LINK_FUNDING_SOURCE: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, USER_ENTITIES.PLAID_ACCOUNT_ID, USER_ENTITIES.PLAID_PUBLIC_TOKEN, USER_ENTITIES.BANK_ACCOUNT_TYPE, USER_ENTITIES.BANK_ROUTING_NUMBER, USER_ENTITIES.BANK_ACCOUNT_NUMBER, COMMON_ENTITIES.NAVIGATOR, 'fetchUserDetails'],
  LINK_FUNDING_SOURCE_SUCCESS: [USER_ENTITIES.SOURCE_REFERENCE_ID],
  LINK_FUNDING_SOURCE_FAILURE: ['error'],
  VERIFY_FUNDING_AMOUNT: [USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, USER_ENTITIES.SOURCE_REFERENCE_ID, USER_ENTITIES.FIRST_AMOUNT, USER_ENTITIES.SECOND_AMOUNT, COMMON_ENTITIES.CALLBACK_FUCTION, COMMON_ENTITIES.NAVIGATOR],
  VERIFY_FUNDING_AMOUNT_SUCCESS: [CHILD_ENTITIES.CHILD_ID],
  VERIFY_FUNDING_AMOUNT_FAILURE: ['error'],

  RESET_BANK_ACCOUNT: [USER_ENTITIES.USER_ID, USER_ENTITIES.SOURCE_REFERENCE_ID, 'resetLogin', COMMON_ENTITIES.CALLBACK_FUCTION, COMMON_ENTITIES.NAVIGATOR],

  RE_AUTHENTICATE_BANK_ACCOUNT: [USER_ENTITIES.USER_ID, USER_ENTITIES.SOURCE_REFERENCE_ID, COMMON_ENTITIES.CALLBACK_FUCTION, COMMON_ENTITIES.NAVIGATOR],

  RE_AUTHENTICATE_BANK_ACCOUNT_WITH_ACCOUNT_ID: [USER_ENTITIES.USER_ID, USER_ENTITIES.PLAID_ACCOUNT_ID, USER_ENTITIES.SOURCE_REFERENCE_ID, COMMON_ENTITIES.CALLBACK_FUCTION, COMMON_ENTITIES.NAVIGATOR],

  SHOW_PENDING_VERIFICATION_ALERT: [COMMON_ENTITIES.NAVIGATOR],
// ------------ setting parameters ------------
  SHOW_ABOUT_US: [COMMON_ENTITIES.NAVIGATOR],
  SHOW_WEB_WINDOW: [SETTINGS_ENTITIES.URL, SETTINGS_ENTITIES.HEADING, COMMON_ENTITIES.NAVIGATOR],
  SET_ROOT_NAVIGATOR: [COMMON_ENTITIES.NAVIGATOR],
  SHOW_SETTINGS: [COMMON_ENTITIES.NAVIGATOR],
  HIDE_SETTINGS: [COMMON_ENTITIES.NAVIGATOR],
  OPEN_SETTINGS: [COMMON_ENTITIES.NAVIGATOR],
  SHOW_ACADEMY: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_SETTING_DETAIL_SCREEN: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_PROFILE: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO: [COMMON_ENTITIES.SCREEN_TYPE, COMMON_ENTITIES.NAVIGATOR],
  SHOW_RECURRING_WIDGET: [CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, GOAL_ENTITIES.RECURRING_AMOUNT, COMMON_ENTITIES.NAVIGATOR],
  SHOW_INVESTOR_QUESTIONS: [COMMON_ENTITIES.NAVIGATOR],
  SHOW_REGULAR_TRANSFERS: [COMMON_ENTITIES.NAVIGATOR],
  NAVIGATE_TO_ABOUT_US: [COMMON_ENTITIES.NAVIGATOR],

  CHANGE_PIN: [COMMON_ENTITIES.NAVIGATOR],
  FORGOT_PASSWORD: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_FORGOT_PASSWORD: [AUTH_ENTITIES.EMAIL, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH, USER_ENTITIES.USER_ID],
  PROCESS_FORGOT_PASSWORD_SUCCESS: [AUTH_ENTITIES.EMAIL, COMMON_ENTITIES.NAVIGATOR],
  PROCESS_FORGOT_PASSWORD_FAILURE: ['error'],

  PROCESS_CONFIRM_PASSWORD: [SETTINGS_ENTITIES.VERIFIED_EMAIL, SETTINGS_ENTITIES.VERIFICATION_CODE, SETTINGS_ENTITIES.PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  PROCESS_CONFIRM_PASSWORD_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_CONFIRM_PASSWORD_FAILURE: ['error'],

  CHANGE_PASSWORD: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_CHANGE_PASSWORD: [AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.PASSWORD, AUTH_ENTITIES.NEW_PASSWORD, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.DISPATCH],
  PROCESS_CHANGE_PASSWORD_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],
  PROCESS_CHANGE_PASSWORD_FAILURE: ['error'],

  FETCH_RECURRING_DATA: [USER_ENTITIES.USER_ID],
  FETCH_RECURRING_DATA_SUCCESS: [SETTINGS_ENTITIES.RECURRING_DATA],
  FETCH_RECURRING_DATA_FAILURE: ['error'],

  FETCH_USER_TRANSACTIONS: [USER_ENTITIES.USER_ID],
  FETCH_USER_TRANSACTIONS_SUCCESS: [USER_ENTITIES.USER_DETAIL],
  FETCH_USER_TRANSACTIONS_FAILURE: ['error'],

  SHOW_DOCUMENTS: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],
  SHOW_DOCUMENTS_SUCCESS: [USER_ENTITIES.USER_DATA, COMMON_ENTITIES.NAVIGATOR],
  SHOW_DOCUMENTS_FAILURE: ['error'],

  SHOW_CONFIRMATIONS: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIRMATIONS_SUCCESS: [USER_ENTITIES.USER_DATA, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIRMATIONS_FAILURE: ['error'],

  VIEW_TRANSFERS: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR],
  VIEW_TRANSFERS_SUCCESS: [USER_ENTITIES.USER_DATA],
  VIEW_TRANSFERS_FAILURE: ['error'],
  VIEW_ACTIVITY: [USER_ENTITIES.USER_ID, COMMON_ENTITIES.NAVIGATOR],
  SHOW_CONFIG: [COMMON_ENTITIES.NAVIGATOR],

  TRANSFER_NOW: [AUTH_ENTITIES.ID_TOKEN, COMMON_ENTITIES.NAVIGATOR],

  SHOW_WEBVIEW: [COMMON_ENTITIES.NAVIGATOR],

  SHOW_PROFILE: [COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_BROKER_DEALER_INFO: [COMMON_ENTITIES.NAVIGATOR],

  // IMAGE RELATED PARAMS
  UPLOAD_PHOTO: [SETTINGS_ENTITIES.IMAGE_METADATA, SETTINGS_ENTITIES.IMAGE_TYPE, AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.ID_TOKEN, USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, CHILD_ENTITIES.IS_UPDATING_CHILD_IMAGE, COMMON_ENTITIES.DISPATCH],

  GET_PHOTO: [SETTINGS_ENTITIES.IMAGE_KEY, SETTINGS_ENTITIES.IMAGE_TYPE, AUTH_ENTITIES.EMAIL, AUTH_ENTITIES.ID_TOKEN, USER_ENTITIES.USER_ID, CHILD_ENTITIES.CHILD_ID, GOAL_ENTITIES.GID, COMMON_ENTITIES.DISPATCH],

  SET_IMAGE_METADATA: [SETTINGS_ENTITIES.IMAGE_METADATA],

  SET_USER_IMAGE_URL: [USER_ENTITIES.IMAGE_URL],

  SET_USER_IMAGE: [USER_ENTITIES.USER_IMAGE],

  DELETE_ACCOUNT: [USER_ENTITIES.USER_ID],

  DISCONNECT_BANK: [COMMON_ENTITIES.NAVIGATOR, USER_ENTITIES.USER_ID],
  DISCONNECT_BANK_SUCCESS: [COMMON_ENTITIES.NAVIGATOR],

  UPDATE_USER_IMAGE_PROCESSING: [USER_ENTITIES.UPDATE_USER_IMAGE_PROCESSING],

  SET_SELECTED_CHILD: [USER_ENTITIES.SELECTED_CHILD],

  SET_CHILD_IMAGE_URL: [CHILD_ENTITIES.IMAGE_URL],

  SET_CHILD_IMAGE: [CHILD_ENTITIES.CHILD_IMAGE, CHILD_ENTITIES.CHILD_ID],

  AUTO_NAVIGATE_ONBOARDING: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.IS_ONBOARDING_FLOW, COMMON_ENTITIES.NAVIGATOR],

  LOG_NUMBER_OF_CHILDREN_AT_START: [CHILD_ENTITIES.NUMBER_OF_CHILDREN_AT_START],

  NAVIGATE_TO_REQUEST_SSN_SCREEN: [USER_ENTITIES.SSN, COMMON_ENTITIES.NAVIGATOR, CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.SHOULD_STORE_USER_SSN],

  NAVIGATE_TO_IDENTITY_ADDRESS_SCREEN: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.IS_ADDING_DESIRE, CHILD_ENTITIES.IS_ADDING_DREAM, COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_INPUT_MANUAL_ADDRESS_SCREEN: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.IS_ADDING_DESIRE, CHILD_ENTITIES.IS_ADDING_DREAM, 'addressData', COMMON_ENTITIES.NAVIGATOR],

  NAVIGATE_TO_CHILD_INVESTING: [CHILD_ENTITIES.CHILD_ID, COMMON_ENTITIES.NAVIGATOR],

  SET_GOAL_IMAGE_URL: [GOAL_ENTITIES.IMAGE_URL],

  SET_GOAL_IMAGE: [GOAL_ENTITIES.GOAL_IMAGE, GOAL_ENTITIES.GID],

  UPDATE_CHILD_IMAGE: [CHILD_ENTITIES.IS_UPDATING_CHILD_IMAGE],

  ADD_CHILD_BIRTH_DATE: [CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.IMAGE_META_DATA, COMMON_ENTITIES.NAVIGATOR, COMMON_ENTITIES.IS_ONBOARDING_FLOW]
}

export const CHILD_PARAMETERS = {
  ADD_AVATAR: [CHILD_ENTITIES.AVATAR],

  ADD_CHILD: [CHILD_ENTITIES.USER_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB],

  ADD_CHILD_SUCCESS: [CHILD_ENTITIES.CHILD_ID, CHILD_ENTITIES.FIRST_NAME, CHILD_ENTITIES.LAST_NAME, CHILD_ENTITIES.DOB],
  ADD_CHILD_FAILURE: ['error']
}
